DELIMITER $$
CREATE PROCEDURE REGISTRAR_SUPERUSUARIO(
	IN _NOMBRES VARCHAR(8),
	IN _APELLIDO_PATERNO VARCHAR(100),
	IN _APELLIDO_MATERNO VARCHAR(100),
	IN _DIRECCION VARCHAR(100), 
    IN _TELEFONO VARCHAR(9), 
    IN _SEXO CHAR(1),
    IN _DNI VARCHAR (8),
    IN _CORREO VARCHAR(40),
    IN _FECHA_NACIMIENTO DATE,
    
    
    IN _CONTRASENIA VARCHAR(40), 
    IN _ESTADO INT(1),
    IN _SUELDO DOUBLE)
BEGIN
    DECLARE _ID_PERSONA INT;
    DECLARE _ID_TRABAJADOR INT; 
	INSERT INTO PERSONA (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DIRECCION, TELEFONO, SEXO, DNI, CORREO, 
                         FECHA_NACIMIENTO) VALUES (_NOMBRES, _APELLIDO_PATERNO, _APELLIDO_MATERNO, _DIRECCION, _TELEFONO, _SEXO, _DNI, _CORREO,
                         _FECHA_NACIMIENTO);
	SET _ID_PERSONA = last_insert_id(); 
    
    INSERT INTO TRABAJADOR (CONTRASENIA, ESTADO, SUELDO, ID_PERSONA_FK) VALUES (_CONTRASENIA, _ESTADO, _SUELDO, _ID_PERSONA);
    
    SET _ID_TRABAJADOR = last_insert_id();
    
    INSERT INTO SUPERUSUARIO (ID_TRABAJADOR_FK, ID_PERSONA_FK) VALUES (_ID_TRABAJADOR, _ID_PERSONA); 
END

CALL REGISTRAR_SUPERUSUARIO('Patricia', 'Cabanillas', 'Vera', 'Av. Escardo 660', '962802959', 'F', '76431838', 'pattyespar@gmail.pe', '1998-03-18', 'crossfire', 1, 10500); 

DELIMITER $
CREATE PROCEDURE LISTAR_SUPERUSUARIOS()
BEGIN
    SELECT pe.ID_PERSONA, tr.ID_TRABAJADOR, su.ID_SUPERUSUARIO, pe.NOMBRES, pe.APELLIDO_PATERNO, pe.APELLIDO_MATERNO, pe.DIRECCION, pe.TELEFONO, 
           pe.SEXO, pe.DNI, pe.CORREO , pe.FECHA_NACIMIENTO, tr.ID_TRABAJADOR, tr.CONTRASENIA, tr.ESTADO, 
           tr.SUELDO
    FROM PERSONA pe, TRABAJADOR tr, SUPERUSUARIO su 
    WHERE pe.ID_PERSONA= tr.ID_PERSONA_FK AND tr.ID_TRABAJADOR=su.ID_TRABAJADOR_FK;
END;



CALL LISTAR_SUPERUSUARIOS();